language: node_js
node_js: 6
script:
  - yarn build
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_url: github.ibm.com
  github_token: $GITHUB_TOKEN
  local_dir: packages/static/lib/test
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: always
